POST http://localhost:5000/register
Content-Type: application/json

{
    "login": "John",
    "password": "Password"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "login": "John1",
    "password": "Password"
}

###
GET http://localhost:5000/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlciI6IkpvaG4iLCJleHAiOjE2MjQ4ODY5NzV9.OLgVwRXtOqP-tyMDPExcQ3uvZnRteU7nx2OuJ1eICKA

###
POST http://localhost:5000/invitate
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlciI6IkpvaG4iLCJleHAiOjE2MjQ4ODY5NzV9.OLgVwRXtOqP-tyMDPExcQ3uvZnRteU7nx2OuJ1eICKA

{
    "user_id": 2
}


###
GET http://localhost:5000/invitate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y
###
POST http://localhost:5000/invitate/accept
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y

{
    "user_id": 1
}

###
GET http://localhost:5000/chat
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y

###
POST http://localhost:5000/message
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y

{
    "target": 1,
    "content": "yeeee"
}

###
GET http://localhost:5000/message
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y

{
    "chat_id": 1
}

###
POST http://localhost:5000/message/status
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwidXNlciI6IkpvaG4xIiwiZXhwIjoxNjI0ODg3MDIyfQ.CXS1RmRAaoQ7GUVmf9AGQKTtbHAZvECiCiHyYkdjq_Y

{
    "msg_ids": [1]
}